# config/config.yaml

defaults:
  - override hydra/job_logging: disabled  # Optional: disable hydra logs

seed: 42
data:
  path: "data/images/1"
  val_ratio: 0.2
  batch_size: 32
  num_workers: 2

train:
  epochs: 5
  lr: 0.001
  use_compile: False
  save: True
  epoch_save: False

wandb:
  project: "image-policy"
  name: "image_net_without_coordConverter"
  log: False