# config/config.yaml

defaults:
  - override hydra/job_logging: disabled  # Optional: disable hydra logs

seed: 42
data:
  file_path: "data/run.hdf5"
  obs_keys: ["image", "velocity", "command"]
  act_keys: ["location"]
  obs_horizon: 1
  act_horizon: 5
  gap: 5
  obs_stride: 1
  act_stride: 5
  val_ratio: 0.2
  batch_size: 32
  num_workers: 2

model:
  backbone: "resnet34"
  pretrained: False
  steps: 5
  commands: 5

train:
  epochs: 3
  lr: 0.001
  use_compile: False
  save: True
  epoch_save: False

wandb:
  project: "image-policy"
  name: "image_net_without_coordConverter"
  log: False